#!/bin/sh

while read file
do
    case "$1" in
        "w") wallmenu "$file" & ;;
        "d") wallmenu --dm "$file" & ;;
        "r") convert -rotate 90 "$file" "$file" ;;
        "R") convert -rotate -90 "$file" "$file" ;;
        "f") convert -flop "$file" "$file" ;;
        "y") echo -n "$file" | tr -d '\n' | xclip -selection clipboard &&
            notify-send "$file copied to clipboard" & ;;
        "Y") readlink -f "$file" | tr -d '\n' | xclip -selection clipboard &&
                notify-send "$(readlink -f "$file") copied to clipboard" & ;;
        "D") [ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
        "g") setsid -f gimp "$file" || notify-send "gimp is not installed." ;;
    esac
done
