k9s:
  liveViewAutoRefresh: true
  screenDumpDir: /home/matteo/.local/state/k9s/screen-dumps
  refreshRate: 2
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  ui:
    skin: catppuccin-mocha
    enableMouse: true
    headless: true
    logoless: true
    crumbsless: true
    reactive: false
    noIcons: false
    defaultsToFullScreen: true
