#!/bin/sh

# start keyboard deamon
killall sxhkd > /dev/null
sxhkd &

# feed fifo file to inform statusbar of wm changes
PANEL_FIFO=/tmp/panel-fifo
[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"
bspc subscribe report > "$PANEL_FIFO" &

# restore previous monitor onfiguration
xrandrmenu --restore

# reset wallpaper
wallmenu --restore &

# launch statusbar and make sure it launches after reboot
[ "$(xrdb -query)" ] || xrdb ~/.config/X11/Xresources
killall launchbar > /dev/null || sleep 3
monitors=$(xrandr --listactivemonitors | awk '/^\s*[0-9]+:/ {print $4}')
for m in $monitors; do
    launchbar "bar1,$m" &
done

# configure desktops
bspwm-tool auto-set-desktops

# configs
# for some reason all the 3 below are needed
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
bspc config border_width 0
bspc config window_gap 12

bspc config automatic_scheme longest_side
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config pointer_follows_monitor true
bspc pointer_modifier mod4
bspc pointer_action1 move
bspc pointer_action2 resize_side
bspc pointer_action3 resize_corner

bspc desktop '1' -l monocle

bspc rule -a 'Gimp' state=floating follow=on
bspc rule -a '*:floatterm' state=floating
bspc rule -a 'Matplotlib' state=floating
bspc rule -a 'qutebrowser' desktop='1'
