#!/bin/sh

# start keyboard deamon
killall sxhkd > /dev/null
setsid -f sxhkd

# feed fifo file to inform statusbar of wm changes
PANEL_FIFO=/tmp/panel-fifo
[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"
bspc subscribe report > "$PANEL_FIFO" &

# restore previous monitor onfiguration
xrandrmenu --restore

# reset wallpaper
wallmenu --restore

# launch statusbar and make sure it launches after reboot
xrdb ~/.config/X11/Xresources
background=$(xrdb -query | awk '/.*background:/ {print $2}')
highlight=$(xrdb -query | awk '/.*color6:/ {print $2}')
killall launchbar > /dev/null || sleep 3
monitors=$(xrandr --listactivemonitors | awk '/^\s*[0-9]+:/ {print $4}')
primary=$(xrandr -q | awk '/primary/ {print $1}')
for m in $monitors; do
    if [ "$m" = "$primary" ]; then
        setsid -f launchbar "bar1,$m"
    else
        setsid -f launchbar "bar2,$m"
    fi
done

# configure desktops
bspwm-tool auto-set-desktops

# configs
# for some reason all the 3 below are needed
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
bspc config border_width 2
bspc config normal_border_color "$background"
bspc config focused_border_color "$highlight"
bspc config window_gap 12

bspc config automatic_scheme longest_side
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config pointer_follows_monitor true
bspc pointer_modifier mod4
bspc pointer_action1 move
bspc pointer_action2 resize_side
bspc pointer_action3 resize_corner

bspc desktop '1' -l monocle
bspc desktop '8' -l monocle

bspc rule -a 'Gimp' state=floating follow=on
bspc rule -a '*:floatterm' state=floating
bspc rule -a 'Matplotlib' state=floating
bspc rule -a 'qutebrowser' desktop='1'
bspc rule -a 'Brave-browser' desktop='1'
bspc rule -a 'Thunderbird' desktop='9'
bspc rule -a 'Signal' desktop='8'
bspc rule -a 'Ferdi' desktop='8'
bspc rule -a 'nuclear' desktop='7'

killall trayer
setsid -f trayer --edge top --align right --expand true --widthtype request --height 20 --margin 6 --iconspacing 6 --monitor primary --transparent true --alpha 0 --tint "0x${background#\#}"
