#!/bin/sh

# read Xresources
xrdb ~/.config/Xresources &

# set keyboard layout
setxkbmap -option compose:ralt us &

# set x cursor
xsetroot -cursor_name left_ptr &

# composite manager (e.g allows transparency)
picom &

# set wallpaper
setwall --refresh &

# access backlight
sudo chmod a+rw /sys/class/backlight/intel_backlight/brightness &

# notifications
dunst &

# clipboard menu
clipmenud &

# calendar
calcurse --daemon &

# keyboard shortcut deamon
sxhkd &

# exec WM or DE
# exec dbus-launch leftwm
exec bspwm

# kill pulseaudio (prevents loading it 2 times)
pulseaudio --kill
